"""Add created by field to event model

Revision ID: 0e92e6e6b9ab
Revises: c31f080bb270
Create Date: 2022-03-10 14:46:33.692428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e92e6e6b9ab'
down_revision = 'c31f080bb270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'created_by')
    # ### end Alembic commands ###
