"""Add date field to event model

Revision ID: 84f8c3445d16
Revises: 0e92e6e6b9ab
Create Date: 2022-03-10 16:13:37.305303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f8c3445d16'
down_revision = '0e92e6e6b9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
