"""Add end_date field

Revision ID: 8654f521bf64
Revises: f530d1f90b77
Create Date: 2022-03-10 20:50:23.317571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8654f521bf64'
down_revision = 'f530d1f90b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'end_date')
    # ### end Alembic commands ###
