"""Add remain tickets count field to event model

Revision ID: b07a5810cdb5
Revises: 8654f521bf64
Create Date: 2022-03-11 14:25:55.409365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07a5810cdb5'
down_revision = '8654f521bf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('remain_tickets_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'remain_tickets_count')
    # ### end Alembic commands ###
